spring:
  rabbitmq:
    host: 10.178.0.9
    username: guest
    password: guest
    port: 5672

  data:
    elasticsearch:
      hosts: 10.146.0.10,10.146.0.11,10.146.0.8,10.146.0.9
      port: 9200


