spring:
  rabbitmq:
    host: 10.178.0.9
    username: guest
    password: guest
    port: 5672

  data:
    elasticsearch:
      hosts: 10.146.0.12,10.146.0.13,10.146.0.14,10.146.0.16
      port: 9200


